// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.708811377 +0200 SAST m=+1.512420807. DO NOT EDIT.

package vk

// WaylandSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWaylandSurfaceCreateFlagsKHR.html
type WaylandSurfaceCreateFlagsKHR Flags
