// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.546859718 +0200 SAST m=+2.307428387. DO NOT EDIT.

package vk

// DirectFBSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDirectFBSurfaceCreateFlagsEXT.html
type DirectFBSurfaceCreateFlagsEXT Flags
