// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.535703474 +0200 SAST m=+2.296272153. DO NOT EDIT.

package vk

// XcbSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXcbSurfaceCreateFlagsKHR.html
type XcbSurfaceCreateFlagsKHR Flags
