// Code generated by go-vk from vk-1.3.290.xml at 2025-10-18 20:30:34.378201 -0400 EDT m=+4.450026785. DO NOT EDIT.

package vk

// ExportMetalObjectTypeFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkExportMetalObjectTypeFlagsEXT.html
type ExportMetalObjectTypeFlagsEXT Flags

// MetalSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMetalSurfaceCreateFlagsEXT.html
type MetalSurfaceCreateFlagsEXT Flags
