// Code generated by go-vk from vk-1.3.290.xml at 2025-10-18 20:30:33.961453 -0400 EDT m=+4.033276686. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
