// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.712607811 +0200 SAST m=+1.516217241. DO NOT EDIT.

package vk

import (
	"golang.org/x/sys/windows"
)

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
