// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.71043469 +0200 SAST m=+1.514044120. DO NOT EDIT.

package vk

// DirectFBSurfaceCreateFlagsEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDirectFBSurfaceCreateFlagsEXT.html
type DirectFBSurfaceCreateFlagsEXT Flags
