// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.736861742 +0200 SAST m=+2.497430411. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
