// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.70929656 +0200 SAST m=+1.512905990. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
