// Code generated by go-vk from vk-1.3.290.xml at 2025-10-18 20:30:33.668827 -0400 EDT m=+3.740649664. DO NOT EDIT.

package vk

// Win32SurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWin32SurfaceCreateFlagsKHR.html
type Win32SurfaceCreateFlagsKHR Flags
