// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.4023124 +0200 SAST m=+2.162881069. DO NOT EDIT.

package vk

// WaylandSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkWaylandSurfaceCreateFlagsKHR.html
type WaylandSurfaceCreateFlagsKHR Flags
