// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.710103754 +0200 SAST m=+1.513713184. DO NOT EDIT.

package vk

// XlibSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXlibSurfaceCreateFlagsKHR.html
type XlibSurfaceCreateFlagsKHR Flags
