// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.74099554 +0200 SAST m=+2.501564199. DO NOT EDIT.

package vk

// MacOSSurfaceCreateFlagsMVK: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkMacOSSurfaceCreateFlagsMVK.html
type MacOSSurfaceCreateFlagsMVK Flags
