// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.711688322 +0200 SAST m=+1.515297752. DO NOT EDIT.

package vk

// XcbSurfaceCreateFlagsKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXcbSurfaceCreateFlagsKHR.html
type XcbSurfaceCreateFlagsKHR Flags
