//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.710050301 +0200 SAST m=+1.513659741. DO NOT EDIT.

package vk

// CreateXlibSurfaceKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateXlibSurfaceKHR.html
func CreateXlibSurfaceKHR(instance Instance, createInfo *XlibSurfaceCreateInfoKHR, allocator *AllocationCallbacks) (surface SurfaceKHR, r error) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkXlibSurfaceCreateInfoKHR
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(vkCreateXlibSurfaceKHR, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkCreateXlibSurfaceKHR = &vkCommand{"vkCreateXlibSurfaceKHR", 4, true, nil}

// GetPhysicalDeviceXlibPresentationSupportKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceXlibPresentationSupportKHR.html
func GetPhysicalDeviceXlibPresentationSupportKHR(physicalDevice PhysicalDevice, queueFamilyIndex uint32, visualID uint32) (r bool, dpy uint32) {
	// dpy is a binding-allocated single return value and will be populated by Vulkan
	ptr_dpy := &dpy

	rval := Bool32(execTrampoline(vkGetPhysicalDeviceXlibPresentationSupportKHR, uintptr(physicalDevice), uintptr(queueFamilyIndex), uintptr(unsafe.Pointer(ptr_dpy)), uintptr(visualID)))
	r = translatePublic_Bool32(rval)

	return
}

var vkGetPhysicalDeviceXlibPresentationSupportKHR = &vkCommand{"vkGetPhysicalDeviceXlibPresentationSupportKHR", 4, true, nil}
