//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.361554743 +0200 SAST m=+2.122123412. DO NOT EDIT.

package vk

import "unsafe"

// CreateWaylandSurfaceKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateWaylandSurfaceKHR.html
func CreateWaylandSurfaceKHR(instance Instance, createInfo *WaylandSurfaceCreateInfoKHR, allocator *AllocationCallbacks) (surface SurfaceKHR, r error) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkWaylandSurfaceCreateInfoKHR
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(vkCreateWaylandSurfaceKHR, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkCreateWaylandSurfaceKHR = &vkCommand{"vkCreateWaylandSurfaceKHR", 4, true, nil}

// GetPhysicalDeviceWaylandPresentationSupportKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceWaylandPresentationSupportKHR.html
func GetPhysicalDeviceWaylandPresentationSupportKHR(physicalDevice PhysicalDevice, queueFamilyIndex uint32) (r bool, display uint32) {
	// display is a binding-allocated single return value and will be populated by Vulkan
	ptr_display := &display

	rval := Bool32(execTrampoline(vkGetPhysicalDeviceWaylandPresentationSupportKHR, uintptr(physicalDevice), uintptr(queueFamilyIndex), uintptr(unsafe.Pointer(ptr_display))))
	r = translatePublic_Bool32(rval)

	return
}

var vkGetPhysicalDeviceWaylandPresentationSupportKHR = &vkCommand{"vkGetPhysicalDeviceWaylandPresentationSupportKHR", 3, true, nil}
