//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.557242586 +0200 SAST m=+2.317811265. DO NOT EDIT.

package vk

import "unsafe"

// CreateDirectFBSurfaceEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateDirectFBSurfaceEXT.html
func CreateDirectFBSurfaceEXT(instance Instance, createInfo *DirectFBSurfaceCreateInfoEXT, allocator *AllocationCallbacks) (surface SurfaceKHR, r error) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkDirectFBSurfaceCreateInfoEXT
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(vkCreateDirectFBSurfaceEXT, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkCreateDirectFBSurfaceEXT = &vkCommand{"vkCreateDirectFBSurfaceEXT", 4, true, nil}

// GetPhysicalDeviceDirectFBPresentationSupportEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceDirectFBPresentationSupportEXT.html
func GetPhysicalDeviceDirectFBPresentationSupportEXT(physicalDevice PhysicalDevice, queueFamilyIndex uint32) (r bool, dfb uint32) {
	// dfb is a binding-allocated single return value and will be populated by Vulkan
	ptr_dfb := &dfb

	rval := Bool32(execTrampoline(vkGetPhysicalDeviceDirectFBPresentationSupportEXT, uintptr(physicalDevice), uintptr(queueFamilyIndex), uintptr(unsafe.Pointer(ptr_dfb))))
	r = translatePublic_Bool32(rval)

	return
}

var vkGetPhysicalDeviceDirectFBPresentationSupportEXT = &vkCommand{"vkGetPhysicalDeviceDirectFBPresentationSupportEXT", 3, true, nil}
