//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.711779928 +0200 SAST m=+1.515389358. DO NOT EDIT.

package vk

// CreateXcbSurfaceKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateXcbSurfaceKHR.html
func CreateXcbSurfaceKHR(instance Instance, createInfo *XcbSurfaceCreateInfoKHR, allocator *AllocationCallbacks) (surface SurfaceKHR, r error) {
	// Parameter is a singular input, requires translation - createInfo
	var pCreateInfo *_vkXcbSurfaceCreateInfoKHR
	if createInfo != nil {
		pCreateInfo = createInfo.Vulkanize()
	}

	// Parameter is a singular input, pass direct - allocator
	var pAllocator unsafe.Pointer
	if allocator != nil {
		pAllocator = unsafe.Pointer(allocator)
	}

	// surface is a binding-allocated single return value and will be populated by Vulkan
	ptr_pSurface := &surface

	r = Result(execTrampoline(vkCreateXcbSurfaceKHR, uintptr(instance), uintptr(unsafe.Pointer(pCreateInfo)), uintptr(unsafe.Pointer(pAllocator)), uintptr(unsafe.Pointer(ptr_pSurface))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkCreateXcbSurfaceKHR = &vkCommand{"vkCreateXcbSurfaceKHR", 4, true, nil}

// GetPhysicalDeviceXcbPresentationSupportKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetPhysicalDeviceXcbPresentationSupportKHR.html
func GetPhysicalDeviceXcbPresentationSupportKHR(physicalDevice PhysicalDevice, queueFamilyIndex uint32, visual_id uint32) (r bool, connection uint32) {
	// connection is a binding-allocated single return value and will be populated by Vulkan
	ptr_connection := &connection

	rval := Bool32(execTrampoline(vkGetPhysicalDeviceXcbPresentationSupportKHR, uintptr(physicalDevice), uintptr(queueFamilyIndex), uintptr(unsafe.Pointer(ptr_connection)), uintptr(visual_id)))
	r = translatePublic_Bool32(rval)

	return
}

var vkGetPhysicalDeviceXcbPresentationSupportKHR = &vkCommand{"vkGetPhysicalDeviceXcbPresentationSupportKHR", 4, true, nil}
