//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.713993016 +0200 SAST m=+1.517602446. DO NOT EDIT.

package vk

// AcquireXlibDisplayEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkAcquireXlibDisplayEXT.html
func AcquireXlibDisplayEXT(physicalDevice PhysicalDevice, display DisplayKHR) (dpy uint32, r error) {
	// dpy is a binding-allocated single return value and will be populated by Vulkan
	ptr_dpy := &dpy

	r = Result(execTrampoline(vkAcquireXlibDisplayEXT, uintptr(physicalDevice), uintptr(unsafe.Pointer(ptr_dpy)), uintptr(display)))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkAcquireXlibDisplayEXT = &vkCommand{"vkAcquireXlibDisplayEXT", 3, true, nil}

// GetRandROutputDisplayEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkGetRandROutputDisplayEXT.html
func GetRandROutputDisplayEXT(physicalDevice PhysicalDevice, rrOutput uint32) (dpy uint32, display DisplayKHR, r error) {
	// dpy is a binding-allocated single return value and will be populated by Vulkan
	ptr_dpy := &dpy

	// display is a binding-allocated single return value and will be populated by Vulkan
	ptr_pDisplay := &display

	r = Result(execTrampoline(vkGetRandROutputDisplayEXT, uintptr(physicalDevice), uintptr(unsafe.Pointer(ptr_dpy)), uintptr(rrOutput), uintptr(unsafe.Pointer(ptr_pDisplay))))

	if r == Result(0) {
		r = SUCCESS
	}
	return
}

var vkGetRandROutputDisplayEXT = &vkCommand{"vkGetRandROutputDisplayEXT", 4, true, nil}
