// Code generated by "stringer -output=enum_string_8.go -type=VideoEncodeTuningModeKHR,VideoEncodeUsageFlagBitsKHR,VideoSessionCreateFlagBitsKHR,ViewportCoordinateSwizzleNV"; DO NOT EDIT.

package vk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_TUNING_MODE_DEFAULT_KHR-0]
	_ = x[VIDEO_ENCODE_TUNING_MODE_HIGH_QUALITY_KHR-1]
	_ = x[VIDEO_ENCODE_TUNING_MODE_LOW_LATENCY_KHR-2]
	_ = x[VIDEO_ENCODE_TUNING_MODE_ULTRA_LOW_LATENCY_KHR-3]
	_ = x[VIDEO_ENCODE_TUNING_MODE_LOSSLESS_KHR-4]
}

const _VideoEncodeTuningModeKHR_name = "VIDEO_ENCODE_TUNING_MODE_DEFAULT_KHRVIDEO_ENCODE_TUNING_MODE_HIGH_QUALITY_KHRVIDEO_ENCODE_TUNING_MODE_LOW_LATENCY_KHRVIDEO_ENCODE_TUNING_MODE_ULTRA_LOW_LATENCY_KHRVIDEO_ENCODE_TUNING_MODE_LOSSLESS_KHR"

var _VideoEncodeTuningModeKHR_index = [...]uint8{0, 36, 77, 117, 163, 200}

func (i VideoEncodeTuningModeKHR) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_VideoEncodeTuningModeKHR_index)-1 {
		return "VideoEncodeTuningModeKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VideoEncodeTuningModeKHR_name[_VideoEncodeTuningModeKHR_index[idx]:_VideoEncodeTuningModeKHR_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_ENCODE_USAGE_DEFAULT_KHR-0]
	_ = x[VIDEO_ENCODE_USAGE_TRANSCODING_BIT_KHR-1]
	_ = x[VIDEO_ENCODE_USAGE_STREAMING_BIT_KHR-2]
	_ = x[VIDEO_ENCODE_USAGE_RECORDING_BIT_KHR-4]
	_ = x[VIDEO_ENCODE_USAGE_CONFERENCING_BIT_KHR-8]
}

const (
	_VideoEncodeUsageFlagBitsKHR_name_0 = "VIDEO_ENCODE_USAGE_DEFAULT_KHRVIDEO_ENCODE_USAGE_TRANSCODING_BIT_KHRVIDEO_ENCODE_USAGE_STREAMING_BIT_KHR"
	_VideoEncodeUsageFlagBitsKHR_name_1 = "VIDEO_ENCODE_USAGE_RECORDING_BIT_KHR"
	_VideoEncodeUsageFlagBitsKHR_name_2 = "VIDEO_ENCODE_USAGE_CONFERENCING_BIT_KHR"
)

var (
	_VideoEncodeUsageFlagBitsKHR_index_0 = [...]uint8{0, 30, 68, 104}
)

func (i VideoEncodeUsageFlagBitsKHR) String() string {
	switch {
	case i <= 2:
		return _VideoEncodeUsageFlagBitsKHR_name_0[_VideoEncodeUsageFlagBitsKHR_index_0[i]:_VideoEncodeUsageFlagBitsKHR_index_0[i+1]]
	case i == 4:
		return _VideoEncodeUsageFlagBitsKHR_name_1
	case i == 8:
		return _VideoEncodeUsageFlagBitsKHR_name_2
	default:
		return "VideoEncodeUsageFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIDEO_SESSION_CREATE_PROTECTED_CONTENT_BIT_KHR-1]
	_ = x[VIDEO_SESSION_CREATE_ALLOW_ENCODE_PARAMETER_OPTIMIZATIONS_BIT_KHR-1000299000]
	_ = x[VIDEO_SESSION_CREATE_INLINE_QUERIES_BIT_KHR-1000515000]
}

const (
	_VideoSessionCreateFlagBitsKHR_name_0 = "VIDEO_SESSION_CREATE_PROTECTED_CONTENT_BIT_KHR"
	_VideoSessionCreateFlagBitsKHR_name_1 = "VIDEO_SESSION_CREATE_ALLOW_ENCODE_PARAMETER_OPTIMIZATIONS_BIT_KHR"
	_VideoSessionCreateFlagBitsKHR_name_2 = "VIDEO_SESSION_CREATE_INLINE_QUERIES_BIT_KHR"
)

func (i VideoSessionCreateFlagBitsKHR) String() string {
	switch {
	case i == 1:
		return _VideoSessionCreateFlagBitsKHR_name_0
	case i == 1000299000:
		return _VideoSessionCreateFlagBitsKHR_name_1
	case i == 1000515000:
		return _VideoSessionCreateFlagBitsKHR_name_2
	default:
		return "VideoSessionCreateFlagBitsKHR(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NV-0]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NV-1]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NV-2]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NV-3]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NV-4]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NV-5]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NV-6]
	_ = x[VIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV-7]
}

const _ViewportCoordinateSwizzleNV_name = "VIEWPORT_COORDINATE_SWIZZLE_POSITIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_X_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Y_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_Z_NVVIEWPORT_COORDINATE_SWIZZLE_POSITIVE_W_NVVIEWPORT_COORDINATE_SWIZZLE_NEGATIVE_W_NV"

var _ViewportCoordinateSwizzleNV_index = [...]uint16{0, 41, 82, 123, 164, 205, 246, 287, 328}

func (i ViewportCoordinateSwizzleNV) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ViewportCoordinateSwizzleNV_index)-1 {
		return "ViewportCoordinateSwizzleNV(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ViewportCoordinateSwizzleNV_name[_ViewportCoordinateSwizzleNV_index[idx]:_ViewportCoordinateSwizzleNV_index[idx+1]]
}
