// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.709425218 +0200 SAST m=+1.513034648. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
