// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.710634895 +0200 SAST m=+1.514244326. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_DIRECTFB_SURFACE_CREATE_INFO_EXT StructureType = 1000346000
)
