// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.826973626 +0200 SAST m=+2.587542295. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
