// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.2636426 +0200 SAST m=+2.024211279. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR StructureType = 1000004000
)
