// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.553715112 +0200 SAST m=+2.314283791. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_DIRECTFB_SURFACE_CREATE_INFO_EXT StructureType = 1000346000
)
