// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.710144502 +0200 SAST m=+1.513753932. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR StructureType = 1000004000
)
