// Code generated by go-vk from vk-1.3.290.xml at 2025-10-18 20:30:33.942161 -0400 EDT m=+4.013984669. DO NOT EDIT.

package vk

// Platform-specific values for VkStructureType
const (
	STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK StructureType = 1000123000
)
