//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.543017108 +0200 SAST m=+2.303585798. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_XCB_SURFACE_EXTENSION_NAME = "VK_KHR_xcb_surface"
	KHR_XCB_SURFACE_SPEC_VERSION   = 6
)
