//go:build darwin

// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.969325196 +0200 SAST m=+2.729893865. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_METAL_OBJECTS_EXTENSION_NAME = "VK_EXT_metal_objects"
	EXT_METAL_OBJECTS_SPEC_VERSION   = 2
	EXT_METAL_SURFACE_EXTENSION_NAME = "VK_EXT_metal_surface"
	EXT_METAL_SURFACE_SPEC_VERSION   = 1
)
