//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.708949463 +0200 SAST m=+1.512558893. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_WAYLAND_SURFACE_EXTENSION_NAME = "VK_KHR_wayland_surface"
	KHR_WAYLAND_SURFACE_SPEC_VERSION   = 6
)
