//go:build darwin
// Code generated by go-vk from vk-1.3.290.xml at 2025-10-18 20:30:33.951506 -0400 EDT m=+4.023330252. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
