//go:build darwin

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.709478861 +0200 SAST m=+1.513088291. DO NOT EDIT.

package vk

// Extension names and versions
const (
	MVK_MACOS_SURFACE_EXTENSION_NAME = "VK_MVK_macos_surface"
	MVK_MACOS_SURFACE_SPEC_VERSION   = 3
)
