//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.710198506 +0200 SAST m=+1.513807936. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_XLIB_SURFACE_EXTENSION_NAME = "VK_KHR_xlib_surface"
	KHR_XLIB_SURFACE_SPEC_VERSION   = 6
)
