//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.267587395 +0200 SAST m=+2.028156085. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_XLIB_SURFACE_EXTENSION_NAME = "VK_KHR_xlib_surface"
	KHR_XLIB_SURFACE_SPEC_VERSION   = 6
)
