//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.713935896 +0200 SAST m=+1.517545326. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_ACQUIRE_XLIB_DISPLAY_EXTENSION_NAME = "VK_EXT_acquire_xlib_display"
	EXT_ACQUIRE_XLIB_DISPLAY_SPEC_VERSION   = 1
)
