//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.7118745 +0200 SAST m=+1.515483930. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_XCB_SURFACE_EXTENSION_NAME = "VK_KHR_xcb_surface"
	KHR_XCB_SURFACE_SPEC_VERSION   = 6
)
