//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.357865478 +0200 SAST m=+2.118434147. DO NOT EDIT.

package vk

// Extension names and versions
const (
	KHR_WAYLAND_SURFACE_EXTENSION_NAME = "VK_KHR_wayland_surface"
	KHR_WAYLAND_SURFACE_SPEC_VERSION   = 6
)
