//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.710586663 +0200 SAST m=+1.514196093. DO NOT EDIT.

package vk

// Extension names and versions
const (
	EXT_DIRECTFB_SURFACE_EXTENSION_NAME = "VK_EXT_directfb_surface"
	EXT_DIRECTFB_SURFACE_SPEC_VERSION   = 1
)
