//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.709969124 +0200 SAST m=+1.513578565. DO NOT EDIT.

package vk

// XlibSurfaceCreateInfoKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXlibSurfaceCreateInfoKHR.html
type XlibSurfaceCreateInfoKHR struct {
	// SType = STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR
	PNext  unsafe.Pointer
	Flags  XlibSurfaceCreateFlagsKHR
	Dpy    *uint32
	Window uint32
}

type _vkXlibSurfaceCreateInfoKHR struct {
	sType  StructureType
	pNext  unsafe.Pointer
	flags  XlibSurfaceCreateFlagsKHR
	dpy    *uint32
	window uint32
}

func (s *_vkXlibSurfaceCreateInfoKHR) Goify() *XlibSurfaceCreateInfoKHR {
	rval := &XlibSurfaceCreateInfoKHR{
		PNext:  (unsafe.Pointer)(s.pNext),
		Flags:  (XlibSurfaceCreateFlagsKHR)(s.flags),
		Dpy:    (*uint32)(s.dpy),
		Window: (uint32)(s.window),
	}
	return rval
}
func (s *XlibSurfaceCreateInfoKHR) Vulkanize() *_vkXlibSurfaceCreateInfoKHR {
	if s == nil {
		return nil
	}
	rval := &_vkXlibSurfaceCreateInfoKHR{
		sType:  STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR, /*c1*/
		pNext:  (unsafe.Pointer)(s.PNext),                   /*cb*/
		flags:  (XlibSurfaceCreateFlagsKHR)(s.Flags),        /*cb*/
		dpy:    (*uint32)(s.Dpy),                            /*cb*/
		window: (uint32)(s.Window),                          /*cb*/
	}
	return rval
}
