//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:07:18.710479056 +0200 SAST m=+1.514088486. DO NOT EDIT.

package vk

// DirectFBSurfaceCreateInfoEXT: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkDirectFBSurfaceCreateInfoEXT.html
type DirectFBSurfaceCreateInfoEXT struct {
	// SType = STRUCTURE_TYPE_DIRECTFB_SURFACE_CREATE_INFO_EXT
	PNext   unsafe.Pointer
	Flags   DirectFBSurfaceCreateFlagsEXT
	Dfb     *uint32
	Surface *uint32
}

type _vkDirectFBSurfaceCreateInfoEXT struct {
	sType   StructureType
	pNext   unsafe.Pointer
	flags   DirectFBSurfaceCreateFlagsEXT
	dfb     *uint32
	surface *uint32
}

func (s *_vkDirectFBSurfaceCreateInfoEXT) Goify() *DirectFBSurfaceCreateInfoEXT {
	rval := &DirectFBSurfaceCreateInfoEXT{
		PNext:   (unsafe.Pointer)(s.pNext),
		Flags:   (DirectFBSurfaceCreateFlagsEXT)(s.flags),
		Dfb:     (*uint32)(s.dfb),
		Surface: (*uint32)(s.surface),
	}
	return rval
}
func (s *DirectFBSurfaceCreateInfoEXT) Vulkanize() *_vkDirectFBSurfaceCreateInfoEXT {
	if s == nil {
		return nil
	}
	rval := &_vkDirectFBSurfaceCreateInfoEXT{
		sType:   STRUCTURE_TYPE_DIRECTFB_SURFACE_CREATE_INFO_EXT, /*c1*/
		pNext:   (unsafe.Pointer)(s.PNext),                       /*cb*/
		flags:   (DirectFBSurfaceCreateFlagsEXT)(s.Flags),        /*cb*/
		dfb:     (*uint32)(s.Dfb),                                /*cb*/
		surface: (*uint32)(s.Surface),                            /*cb*/
	}
	return rval
}
