//go:build linux

// Code generated by go-vk from vk.xml at 2026-01-08 17:35:28.452672478 +0200 SAST m=+2.213241147. DO NOT EDIT.

package vk

import "unsafe"

// XcbSurfaceCreateInfoKHR: See https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXcbSurfaceCreateInfoKHR.html
type XcbSurfaceCreateInfoKHR struct {
	// SType = STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR
	PNext      unsafe.Pointer
	Flags      XcbSurfaceCreateFlagsKHR
	Connection *uint32
	Window     uint32
}

type _vkXcbSurfaceCreateInfoKHR struct {
	sType      StructureType
	pNext      unsafe.Pointer
	flags      XcbSurfaceCreateFlagsKHR
	connection *uint32
	window     uint32
}

func (s *_vkXcbSurfaceCreateInfoKHR) Goify() *XcbSurfaceCreateInfoKHR {
	rval := &XcbSurfaceCreateInfoKHR{
		PNext:      (unsafe.Pointer)(s.pNext),
		Flags:      (XcbSurfaceCreateFlagsKHR)(s.flags),
		Connection: (*uint32)(s.connection),
		Window:     (uint32)(s.window),
	}
	return rval
}
func (s *XcbSurfaceCreateInfoKHR) Vulkanize() *_vkXcbSurfaceCreateInfoKHR {
	if s == nil {
		return nil
	}
	rval := &_vkXcbSurfaceCreateInfoKHR{
		sType:      STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR, /*c1*/
		pNext:      (unsafe.Pointer)(s.PNext),                  /*cb*/
		flags:      (XcbSurfaceCreateFlagsKHR)(s.Flags),        /*cb*/
		connection: (*uint32)(s.Connection),                    /*cb*/
		window:     (uint32)(s.Window),                         /*cb*/
	}
	return rval
}
